name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Get latest commit hash
        id: get_hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get MC version
        uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
        id: read_properties
        with:
          path: gradle.properties
          properties: minecraft_version enabled_platforms mod_version mod_id

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            caches
            loom-cache

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Find jars
        id: find_jars
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "jars<<$EOF" >> $GITHUB_OUTPUT
          find . -regextype posix-extended -regex "\.\/($(tr "," "|" <<< ${{ steps.read_properties.outputs.enabled_platforms }}))\/build\/libs\/${{ steps.read_properties.outputs.mod_id }}-${{ steps.read_properties.outputs.mod_version }}-${{ steps.get_hash.outputs.sha_short }}\+${{ steps.read_properties.outputs.minecraft_version }}-($(tr "," "|" <<< ${{ steps.read_properties.outputs.enabled_platforms }})).jar" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ steps.read_properties.outputs.mod_id }}-${{ steps.read_properties.outputs.mod_version }}-${{ steps.get_hash.outputs.sha_short }}+${{ steps.read_properties.outputs.minecraft_version }}
          path: ${{ steps.find_jars.outputs.jars }}
